#!/bin/bash

clear
echo -e "================================================="
echo -e "# Script Auto Install SSH & OpenVPN             #"
echo -e "#-----------------------------------------------#"
echo -e "# For Debian 7 32 bit & 64 bit                  #"
echo -e "# For VPS with KVM and VMWare virtualization    #"
echo -e "# Modified R3V1V3R                              #"
echo -e "#-----------------------------------------------#"
echo -e "Thanks To"
echo -e "---------"
echo -e "R3V1V3R 1NT3RN3T L1VR3"
echo -e "Admin And All Member KPN Family"
echo -e "Google"
echo -e "Bustami Arifin (Original script)"
echo -e ""
echo -e ""
echo -e "----"
echo -e "CPM/OOCPM"
echo -e "KPN IMO"
echo -e "K.A.G"
echo -e "#-----------------------------------------------#"
echo -e "================================================="
