#!/bin/bash
clear
echo -e "\033[0;34m#==========================================#\033[0;32m"
echo -e "#    Script Auto Install SSH & OpenVPN     #\033[0;34m"
echo -e "#------------------------------------------#\033[0;32m"
echo -e "# Para Debian 8 32 bit & 64 bit            #"
echo -e "# Para VPS com KVM e VMWare virtualização  #"
echo -e "# Modificado por R3V1V3R 1NTERN3T L1VR3    #\033[0;34m"
echo -e "#------------------------------------------#\033[0;32m"
echo -e "#-----------AGRADECIMENTOS-----------------#\033[0;34m"
echo -e "#------------------------------------------#\033[0;32m"
echo -e "#------R3V1V3R 1NT3RN3T L1VR3--------------#\033[0;33m"
echo -e "#          TheGrapevine                    #"
echo -e "#             Google                       #"
echo -e "#    Bustami Arifin (Script Original)      #\033[0;34m"
echo -e "#------------------------------------------#\033[0;34m"
echo -e "#------------------------------------------#\033[0;33m"
echo -e "#             <<JUDIBA>>                   #"
echo -e "#              @judiba                     #"
echo -e "#              Mสrc๏ήe                     #"
echo -e "#           @thegrapevine                  #\033[0;34m"
echo -e "#------------------------------------------#"
echo -e "#==========================================#\033[0;33m"
