#!/bin/bash

clear
echo -e "================================================="
echo -e "# Script Auto Install SSH & OpenVPN             #"
echo -e "#-----------------------------------------------#"
echo -e "# Para Debian 8 32 bit & 64 bit                 #"
echo -e "# Para VPS com KVM e VMWare virtualização       #"
echo -e "# Modificado por R3V1V3R 1NTERN3T L1VR3         #"
echo -e "#-----------------------------------------------#"
echo -e "AGRADECIMENTOS"
echo -e "---------"
echo -e "R3V1V3R 1NT3RN3T L1VR3"
echo -e "TheGrapevine"
echo -e "Google"
echo -e "Bustami Arifin (Script Original)"
echo -e "---------"
echo -e "---------"
echo -e "<<JUDIBA>>"
echo -e "@judiba"
echo -e "Mสrc๏ήe"
echo -e "@thegrapevine"
echo -e "#-----------------------------------------------#"
echo -e "================================================="
