#!/bin/bash
echo -e ""
echo -e "» menu          : Exibe uma lista de comandos"
echo -e "» user-add      : Crie uma conta SSH & OpenVPN"
echo -e "» trial         : Crie uma conta de teste"
echo -e "» user-del      : Excluir a conta SSH & OpenVPN"
echo -e "» user-login    : Verifique o login do usuário"
echo -e "» user-list     : Lista de membros SSH & OpenVPN"
echo -e "» expdel        : Excluir usuário expirado"
echo -e "» resvis        : Reinicie o serviço dropbear, webmin"
echo -e "                 squid3, OpenVPN,Stunnel e SSH"
echo -e "» reboot        : Reinicie VPS"
echo -e "» speedtest     : Speedtest VPS"
echo -e "» info          : Exibe informações do sistema"
echo -e "» about         : Instalação automática do script de informações"
echo -e "» exit          : Saia do terminal SSH"
echo -e "R3V1V3R"
